// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.modelgen.writer;

import io.github.thinkfastpl.harbororm.api.annotations.Column;
import io.github.thinkfastpl.harbororm.api.metadata.EnumMappingType;
import io.github.thinkfastpl.harbororm.modelgen.metadata.*;

import java.util.List;
import java.util.stream.Collectors;

class QColumnWriterUtils {

    static String generateColumnDeclaration(ColumnMetadata metadata) {
        if (metadata.json()) {
            return "public final QJsonColumn<%s> %s;".formatted(metadata.type().getTypeClassNameForGenericUse(), metadata.fieldName());
        } else if (metadata.converterMetadata() == null) {
            return "public final QColumn<%s> %s;".formatted(metadata.type().getTypeClassNameForGenericUse(), metadata.fieldName());
        } else {
            return "public final QColumnConverted<%s, %s> %s;".formatted(
                    metadata.type().getTypeClassNameForGenericUse(),
                    metadata.converterMetadata().convDbTypeNameForGenericUse(),
                    metadata.fieldName()
            );
        }
    }

    static String generateColumnConstructorInit(ColumnMetadata metadata) {
        return generateColumnConstructorInit(metadata, false);
    }

    static String generateColumnConstructorInit(ColumnMetadata metadata, boolean attributeOverrides) {
        final String qColumnInitCode = generateQColumnInitCode(metadata, (Column) null);
        if (attributeOverrides) {
            return """
                   this.%s = (QColumn<%s>) attributeOverrides.getOrDefault(
                       "%s",
                       %s
                   );"""
                    .formatted(
                            metadata.fieldName(),
                            metadata.type().getTypeClassNameForGenericUse(), metadata.fieldName(),
                            qColumnInitCode
                    );
        } else {
            return """
                   this.%s = %s;""".formatted(metadata.fieldName(), qColumnInitCode);
        }
    }

    public static String generateQColumnInitCode(ColumnMetadata metadata, Column overriddenData) {
        final String columnName = overriddenData != null ? overriddenData.name() : metadata.columnName();
        final boolean insertable = overriddenData != null ? overriddenData.insertable() : metadata.insertable();
        final boolean updatable = overriddenData != null ? overriddenData.updatable() : metadata.updatable();
        final boolean nullable = overriddenData != null ? overriddenData.nullable() : metadata.nullable();

        final String factoryClass = metadata.json() ? "QJsonColumn" : "QColumn";

        if (metadata.converterMetadata() == null) {
            return "%s.regular(%s.class, alias, null, \"%s\", \"%s\", %s, %s, %s, %s, null, %s, %s, %s, %s, %s, %s, %s)"
                    .formatted(
                            factoryClass,
                            metadata.type().getTypeClassNameForGenericUse(),
                            metadata.fieldName(),
                            columnName.replace("\"", "\\\""),
                            Boolean.toString(metadata.id()),
                            Boolean.toString(metadata.autoGenerated()),
                            Boolean.toString(metadata.sequenceGenerator() != null),
                            generateSequenceGeneratorData(metadata.sequenceGenerator()),
                            Boolean.toString(insertable),
                            Boolean.toString(updatable),
                            Boolean.toString(nullable),
                            Boolean.toString(metadata.version()),
                            generateEnumMapping(metadata.enumMappingType()),
                            generateTypesInit(metadata.typesMetadata()),
                            generateTypeHandlerInit(metadata.typeHandlerMetadata())
                    );
        } else {
            return "%s.converted(%s.class, %s.class, alias, null, \"%s\", \"%s\", %s, %s, %s, null, %s, %s, %s, %s, %s, %s, %s, %s)"
                    .formatted(
                            factoryClass,
                            metadata.type().getTypeClassNameForGenericUse(),
                            metadata.converterMetadata().convDbTypeNameForGenericUse(),
                            metadata.fieldName(),
                            columnName.replace("\"", "\\\""),
                            Boolean.toString(metadata.id()),
                            Boolean.toString(metadata.autoGenerated()),
                            Boolean.toString(metadata.sequenceGenerator() != null),
                            generateConverterData(metadata.converterMetadata()),
                            Boolean.toString(insertable),
                            Boolean.toString(updatable),
                            Boolean.toString(nullable),
                            Boolean.toString(metadata.version()),
                            generateEnumMapping(metadata.enumMappingType()),
                            generateTypesInit(metadata.typesMetadata()),
                            generateTypeHandlerInit(metadata.typeHandlerMetadata())
                    );
        }
    }

    public static String generateQColumnInitCode(ColumnMetadata metadata, String columnName) {
        final String factoryClass = metadata.json() ? "QJsonColumn" : "QColumn";

        if (metadata.converterMetadata() == null) {
            return "%s.regular(%s.class, alias, null, \"%s\", \"%s\", %s, %s, %s, %s, null, %s, %s, %s, %s, %s, %s, %s)"
                    .formatted(
                            factoryClass,
                            metadata.type().getTypeClassNameForGenericUse(),
                            metadata.fieldName(),
                            columnName.replace("\"", "\\\""),
                            Boolean.toString(metadata.id()),
                            Boolean.toString(metadata.autoGenerated()),
                            Boolean.toString(metadata.sequenceGenerator() != null),
                            generateSequenceGeneratorData(metadata.sequenceGenerator()),
                            Boolean.toString(metadata.insertable()),
                            Boolean.toString(metadata.updatable()),
                            Boolean.toString(metadata.nullable()),
                            Boolean.toString(metadata.version()),
                            generateEnumMapping(metadata.enumMappingType()),
                            generateTypesInit(metadata.typesMetadata()),
                            generateTypeHandlerInit(metadata.typeHandlerMetadata())
                    );
        } else {
            return "%s.converted(%s.class, %s.class, alias, null, \"%s\", \"%s\", %s, %s, %s, null, %s, %s, %s, %s, %s, %s, %s, %s)"
                    .formatted(
                            factoryClass,
                            metadata.type().getTypeClassNameForGenericUse(),
                            metadata.converterMetadata().convDbTypeNameForGenericUse(),
                            metadata.fieldName(),
                            columnName.replace("\"", "\\\""),
                            Boolean.toString(metadata.id()),
                            Boolean.toString(metadata.autoGenerated()),
                            Boolean.toString(metadata.sequenceGenerator() != null),
                            generateConverterData(metadata.converterMetadata()),
                            Boolean.toString(metadata.insertable()),
                            Boolean.toString(metadata.updatable()),
                            Boolean.toString(metadata.nullable()),
                            Boolean.toString(metadata.version()),
                            generateEnumMapping(metadata.enumMappingType()),
                            generateTypesInit(metadata.typesMetadata()),
                            generateTypeHandlerInit(metadata.typeHandlerMetadata())
                    );
        }
    }

    static String generateColumnOnElementCollection(ColumnMetadata metadata) {
        return "QColumn.onElementCollection(%s.class, \"%s\", %s, %s, %s, %s)".formatted(
                metadata.type().getTypeClassNameForGenericUse(),
                metadata.columnName().replace("\"", "\\\""),
                generateConverterData(metadata.converterMetadata()),
                generateEnumMapping(metadata.enumMappingType()),
                generateTypesInit(metadata.typesMetadata()),
                generateTypeHandlerInit(metadata.typeHandlerMetadata())
        );
    }

    private static String generateConverterData(ConverterMetadata metadata) {
        if (metadata == null) {
            return "null";
        }

        return "new ConverterData(%s.class, %s.class, %s.class)".formatted(metadata.converterTypeName(), metadata.convEntityTypeNameForGenericUse(), metadata.convDbTypeNameForGenericUse());
    }

    private static String generateEnumMapping(EnumMappingType enumMappingType) {
        return enumMappingType == null ? "null" : "EnumMappingType." + enumMappingType.name();
    }

    private static String generateSequenceGeneratorData(SequenceGeneratorMetadata sequenceGeneratorMetadata) {
        if (sequenceGeneratorMetadata == null) {
            return "null";
        }
        return "new SequenceGeneratorData(\"%s\")".formatted(sequenceGeneratorMetadata.sequenceName().replace("\\", "\\\\").replace("\"", "\\\""));
    }

    private static String generateTypeHandlerInit(TypeHandlerMetadata metadata) {
        if (metadata == null) {
            return "null";
        }

        List<String> entries = metadata.handlersByDialect().entrySet().stream()
                .map(entry -> "\"%s\", (Class<?>) %s.class".formatted(
                        entry.getKey().replace("\"", "\\\""),
                        entry.getValue()
                ))
                .collect(Collectors.toList());

        return generateMapOf(entries, "<String, Class<?>>");
    }

    private static String generateTypesInit(TypesMetadata metadata) {
        if (metadata == null) {
            return "null";
        }

        List<String> entries = metadata.typesByDialect().entrySet().stream()
                .map(entry -> "\"%s\", \"%s\"".formatted(
                        entry.getKey().replace("\"", "\\\""),
                        entry.getValue().replace("\"", "\\\"")
                ))
                .collect(Collectors.toList());

        return generateMapOf(entries);
    }

    static String generateMapOf(List<String> entries) {
        return generateMapOf(entries, "");
    }

    static String generateMapOf(List<String> entries, String typeParams) {
        if (entries.size() <= 10) {
            return "Map.%sof(%s)".formatted(typeParams, String.join(", ", entries));
        } else {
            String entriesStr = entries.stream()
                    .map(e -> "Map.entry(%s)".formatted(e))
                    .collect(Collectors.joining(", "));
            return "Map.%sofEntries(%s)".formatted(typeParams, entriesStr);
        }
    }
}
