services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - harbor-pg:/var/lib/postgresql/data
    ports:
      - "10501:5432"

  maria:
    image: mariadb:12.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
    volumes:
      - harbor-mariadb:/var/lib/mysql
    ports:
      - "10502:3306"

  mysql:
    image: mysql:8.4.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - harbor-mysql:/var/lib/mysql
    ports:
      - "10503:3306"

volumes:
  harbor-pg:
  harbor-mariadb:
  harbor-mysql:
