// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.metadata;

import java.util.Map;

/**
 * A {@link QColumn} implementation with an attached {@link io.github.thinkfastpl.harbororm.api.converter.AttributeConverter},
 * bridging between the entity Java type ({@code T}) and the database Java type ({@code C}).
 *
 * <p>This is a package-private class created by {@link QColumn#converted}. It implements
 * {@link QColumnConverted} and provides a lazily-initialized unconverted column via
 * {@link #asUnconverted()} using double-checked locking for thread safety.
 *
 * @param <T> the entity-side Java type
 * @param <C> the database-side Java type
 * @see QColumnConverted
 * @see DefaultQColumn
 */
class ConvertedQColumn<T, C> extends DefaultQColumn<T> implements QColumnConverted<T, C> {

    private final Class<C> dbJavaType;

    private volatile QColumn<C> unconverted = null;

    ConvertedQColumn(
            Class<T> convertJavaType,
            Class<C> dbJavaType,
            String tableAlias,
            String alias,
            String propertyName,
            String columnName,
            boolean id,
            boolean autoGenerated,
            boolean sequenceGenerated,
            SequenceGeneratorData sequenceGeneratorData,
            ConverterData converterData,
            boolean insertable,
            boolean updatable,
            boolean nullable,
            boolean version,
            EnumMappingType enumMappingType,
            Map<String, String> customTypes,
            Map<String, Class<?>> typeHandlerClasses
    ) {
        super(
                convertJavaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated, sequenceGeneratorData,
                converterData, insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses
        );
        this.dbJavaType = dbJavaType;
    }

    @Override
    public Class<C> getDbJavaType() {
        return dbJavaType;
    }

    @Override
    public QColumn<C> asUnconverted() {
        if (this.unconverted == null) {
            synchronized (this) {
                if (this.unconverted == null) {
                    this.unconverted = new DefaultQColumn<>(
                            dbJavaType,
                            getTableAlias(),
                            getAlias(),
                            getPropertyName(),
                            getColumnName(),
                            isId(),
                            isAutoGenerated(),
                            isSequenceGenerated(),
                            getSequenceGeneratorMetadata().orElse(null),
                            null,
                            isInsertable(),
                            isUpdatable(),
                            isNullable(),
                            isVersion(),
                            null,
                            getCustomTypes(),
                            null
                    );
                }
            }
        }
        return this.unconverted;
    }
}
