// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.metadata;

import lombok.NonNull;

import java.util.Map;

/**
 * A {@link QJsonColumn} implementation with an attached {@link io.github.thinkfastpl.harbororm.api.converter.AttributeConverter}.
 *
 * <p>Combines the converter support of {@link ConvertedQColumn} with the JSON operators of
 * {@link QJsonColumn}. Created by {@link QJsonColumn#converted}. Overrides
 * {@link #getColumnContext(String)} to set the JSON flag on the returned {@link ColumnContext}.
 *
 * @param <T> the entity-side Java type
 * @param <C> the database-side Java type
 * @see QJsonColumn
 * @see ConvertedQColumn
 */
class ConvertedQJsonColumn<T, C> extends ConvertedQColumn<T, C> implements QJsonColumn<T> {

    ConvertedQJsonColumn(
            Class<T> convertJavaType, Class<C> dbJavaType,
            String tableAlias, String alias,
            String propertyName, String columnName,
            boolean id, boolean autoGenerated, boolean sequenceGenerated,
            SequenceGeneratorData sequenceGeneratorData, ConverterData converterData,
            boolean insertable, boolean updatable, boolean nullable, boolean version,
            EnumMappingType enumMappingType, Map<String, String> customTypes,
            Map<String, Class<?>> typeHandlerClasses
    ) {
        super(convertJavaType, dbJavaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated,
                sequenceGeneratorData, converterData,
                insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses);
    }

    @Override
    public ColumnContext getColumnContext(@NonNull String dialectName) {
        ColumnContext parentContext = super.getColumnContext(dialectName);
        if (parentContext == null) {
            return new ColumnContext(null, null, true);
        }
        return parentContext.withJson(true);
    }
}
