// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.metadata;

import lombok.NonNull;

import java.util.Map;

/**
 * Default implementation of {@link QJsonColumn} that extends {@link DefaultQColumn} with JSON column context.
 *
 * <p>This is a package-private class created by {@link QJsonColumn#regular}. It overrides
 * {@link #getColumnContext(String)} to set the JSON flag on the returned {@link ColumnContext}.
 *
 * @param <T> the Java type of the column value
 * @see QJsonColumn
 * @see DefaultQColumn
 */
class DefaultQJsonColumn<T> extends DefaultQColumn<T> implements QJsonColumn<T> {

    DefaultQJsonColumn(
            Class<T> javaType, String tableAlias, String alias,
            String propertyName, String columnName,
            boolean id, boolean autoGenerated, boolean sequenceGenerated,
            SequenceGeneratorData sequenceGeneratorData, ConverterData converterData,
            boolean insertable, boolean updatable, boolean nullable, boolean version,
            EnumMappingType enumMappingType, Map<String, String> customTypes,
            Map<String, Class<?>> typeHandlerClasses
    ) {
        super(javaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated,
                sequenceGeneratorData, converterData,
                insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses);
    }

    @Override
    public ColumnContext getColumnContext(@NonNull String dialectName) {
        ColumnContext columnContext = super.getColumnContext(dialectName);
        if (columnContext == null) {
            return new ColumnContext(null, null, true);
        }
        return columnContext.withJson(true);
    }
}
