// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.metadata;

import io.github.thinkfastpl.harbororm.api.dialect.StandardDialects;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NonNull;

import java.util.Map;
import java.util.Optional;

/**
 * Default implementation of {@link QColumn} that stores all column metadata fields.
 *
 * <p>This is a package-private class created by the {@link QColumn#regular} factory method.
 * It validates that {@code @Convert} and {@code @Enumerated} are not both present on the same column,
 * and automatically creates the appropriate {@link io.github.thinkfastpl.harbororm.api.converter.AttributeConverter}
 * for enumerated columns.
 *
 * @param <C> the Java type of the column value
 * @see QColumn
 * @see ConvertedQColumn
 */
class DefaultQColumn<C> implements QColumn<C> {
    private final Class<C> javaType;
    private final String tableAlias;
    private final String alias;
    private final String propertyName;
    private final String columnName;
    private final boolean id;
    private final boolean autoGenerated;
    private final boolean sequenceGenerated;
    private final SequenceGeneratorData sequenceGeneratorData;
    private final ConverterData converterData;
    private final boolean insertable;
    private final boolean updatable;
    private final boolean nullable;
    private final boolean version;
    private final EnumMappingType enumMappingType;

    @Getter(AccessLevel.PROTECTED)
    private final Map<String, String> customTypes;

    @Getter(AccessLevel.PROTECTED)
    private final Map<String, Class<?>> typeHandlerClasses;

    @SuppressWarnings({"rawtypes", "unchecked"})
    DefaultQColumn(
            Class<C> javaType,
            String tableAlias,
            String alias,
            String propertyName,
            String columnName,
            boolean id,
            boolean autoGenerated,
            boolean sequenceGenerated,
            SequenceGeneratorData sequenceGeneratorData,
            ConverterData converterData,
            boolean insertable,
            boolean updatable,
            boolean nullable,
            boolean version,
            EnumMappingType enumMappingType,
            Map<String, String> customTypes,
            Map<String, Class<?>> typeHandlerClasses
    ) {
        this.javaType = javaType;
        this.tableAlias = tableAlias;
        this.alias = alias;
        this.propertyName = propertyName;
        this.columnName = columnName;
        this.id = id;
        this.autoGenerated = autoGenerated;
        this.sequenceGenerated = sequenceGenerated;
        this.sequenceGeneratorData = sequenceGeneratorData;
        this.insertable = insertable;
        this.updatable = updatable;
        this.nullable = nullable;
        this.version = version;

        if (converterData != null && enumMappingType != null) {
            throw new IllegalArgumentException("Both @Convert and @Enumerated must not be used on the same column");
        }

        if (enumMappingType != null) {
            this.converterData = switch (enumMappingType) {
                case STRING -> new ConverterData(
                        new EnumeratedStringAttributeConverter(javaType),
                        javaType,
                        String.class
                );
                case ORDINAL -> new ConverterData(
                        new EnumeratedOrdinalAttributeConverter(javaType),
                        javaType,
                        Integer.class
                );
            };
        } else {
            this.converterData = converterData;
        }

        this.enumMappingType = enumMappingType;
        this.customTypes = customTypes;
        this.typeHandlerClasses = typeHandlerClasses;
    }

    @Override
    public Class<C> getJavaType() {
        return this.javaType;
    }

    @Override
    public String getTableAlias() {
        return this.tableAlias;
    }

    @Override
    public String getAlias() {
        return this.alias;
    }

    @Override
    public String getResultColumnLabel() {
        if (alias != null) {
            return alias;
        }
        return columnName;
    }

    @Override
    public String getPropertyName() {
        return propertyName;
    }

    @Override
    public String getColumnName() {
        return this.columnName;
    }

    @Override
    public QColumn<C> as(String alias) {
        return new DefaultQColumn<>(
                javaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated, sequenceGeneratorData,
                converterData, insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses
        );
    }

    @Override
    public boolean isId() {
        return this.id;
    }

    @Override
    public boolean isAutoGenerated() {
        return this.autoGenerated;
    }

    @Override
    public boolean isSequenceGenerated() {
        return this.sequenceGenerated;
    }

    @Override
    public Optional<SequenceGeneratorData> getSequenceGeneratorMetadata() {
        return Optional.ofNullable(sequenceGeneratorData);
    }

    @Override
    public ColumnContext getColumnContext(@NonNull String dialectName) {
        String customType = null;
        if (customTypes != null) {
            customType = customTypes.get(dialectName);
            if (customType == null) {
                customType = customTypes.get(StandardDialects.ANY);
            }
        }

        Class<?> handlerClass = null;
        if (typeHandlerClasses != null) {
            handlerClass = typeHandlerClasses.get(dialectName);
            if (handlerClass == null) {
                handlerClass = typeHandlerClasses.get(StandardDialects.ANY);
            }
        }

        if (customType != null || converterData != null || handlerClass != null) {
            return new ColumnContext(customType, converterData, false, handlerClass);
        }
        return null;
    }

    @Override
    public boolean isInsertable() {
        return this.insertable;
    }

    @Override
    public boolean isUpdatable() {
        return this.updatable;
    }

    @Override
    public boolean isNullable() {
        return this.nullable;
    }

    @Override
    public boolean isVersion() {
        return this.version;
    }
}
