// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.metadata;

import io.github.thinkfastpl.harbororm.api.expression.Condition;
import io.github.thinkfastpl.harbororm.api.expression.Expression;
import lombok.NonNull;

import java.util.Collection;
import java.util.Map;
import java.util.Optional;

/**
 * Type-safe column reference that is the primary building block for HarborORM queries.
 *
 * <p>{@code QColumn} extends both {@link QComparableAttribute} (for entity metadata operations)
 * and {@link Expression} (for the full query DSL). This allows columns to be used in
 * {@code SELECT}, {@code WHERE}, {@code ORDER BY}, {@code GROUP BY}, and {@code HAVING} clauses.
 *
 * <p>Instances are created by the annotation processor and exposed as public fields on generated
 * metadata classes ({@code Q<EntityName>} and {@code <TableName>Table}).
 *
 * <p>Example:
 * <pre>{@code
 * QSomeEntity ENTITY = new QSomeEntity(null);
 * // ENTITY.name is a QColumn<String>
 * session.selectEntity(ENTITY)
 *     .where(ENTITY.name.eq("value").and(ENTITY.id.gt(100)))
 *     .orderBy(ENTITY.name.asc())
 *     .fetchAll();
 * }</pre>
 *
 * <p>Factory methods are provided for creating column instances:
 * <ul>
 *   <li>{@link #regular} - standard column with all configuration options</li>
 *   <li>{@link #converted} - column with an attached {@link io.github.thinkfastpl.harbororm.api.converter.AttributeConverter}</li>
 *   <li>{@link #simple} - minimal column with only type, alias, and name</li>
 *   <li>{@link #onElementCollection} - column for use in element collection tables</li>
 *   <li>{@link #of(JoinColumnData)} - column derived from join column metadata</li>
 * </ul>
 *
 * @param <T> the Java type of the column value
 * @see QJsonColumn
 * @see QColumnConverted
 * @see Expression
 */
public interface QColumn<T> extends QAttribute, QComparableAttribute<T>, Expression<T> {

    /**
     * Returns the table alias this column belongs to, or {@code null} if unaliased.
     *
     * @return the table alias
     */
    String getTableAlias();

    /**
     * {@inheritDoc}
     */
    String getPropertyName();

    /**
     * Returns the database column name.
     *
     * @return the SQL column name
     */
    String getColumnName();

    /**
     * Returns {@code true} if this column is the primary key (annotated with {@code @Id}).
     *
     * @return whether this is the ID column
     */
    boolean isId();

    /**
     * Returns {@code true} if the ID value is auto-generated by the database (annotated with {@code @AutoGenerated}).
     *
     * @return whether the column value is database-generated
     */
    boolean isAutoGenerated();

    /**
     * Returns {@code true} if the ID value is generated from a database sequence (annotated with {@code @SequenceGenerated}).
     *
     * @return whether the column value is sequence-generated
     */
    boolean isSequenceGenerated();

    /**
     * Returns {@code true} if this column is included in {@code INSERT} statements.
     *
     * @return whether the column is insertable
     */
    boolean isInsertable();

    /**
     * Returns {@code true} if this column is included in {@code UPDATE} statements.
     *
     * @return whether the column is updatable
     */
    boolean isUpdatable();

    /**
     * Returns {@code true} if this column allows {@code NULL} values.
     *
     * @return whether the column is nullable
     */
    boolean isNullable();

    /**
     * Returns {@code true} if this column is the optimistic locking version column (annotated with {@code @Version}).
     *
     * @return whether this is the version column
     */
    boolean isVersion();

    /**
     * Returns the sequence generator metadata if this column uses {@code @SequenceGenerated}.
     *
     * @return an {@link Optional} containing the sequence data, or empty
     */
    Optional<SequenceGeneratorData> getSequenceGeneratorMetadata();

    @Override
    default Condition eq(T value) {
        return Expression.super.eq(value);
    }

    @Override
    default Condition in(Collection<T> values) {
        return Expression.super.in(values);
    }

    /**
     * Creates a standard column reference with full configuration.
     *
     * <p>This is the primary factory method used by generated metadata classes.
     *
     * @param <T>                    the Java type of the column
     * @param javaType               the Java class of the column value
     * @param tableAlias             the table alias, or {@code null}
     * @param alias                  the column alias (for SELECT AS), or {@code null}
     * @param propertyName           the entity property name, or {@code null}
     * @param columnName             the database column name
     * @param id                     whether this is the primary key column
     * @param autoGenerated          whether the value is database-generated
     * @param sequenceGenerated      whether the value is sequence-generated
     * @param sequenceGeneratorData  sequence metadata, or {@code null}
     * @param converterData          converter metadata, or {@code null}
     * @param insertable             whether included in INSERT statements
     * @param updatable              whether included in UPDATE statements
     * @param nullable               whether the column allows NULL
     * @param version                whether this is the optimistic lock version column
     * @param enumMappingType        the enum mapping strategy, or {@code null} if not an enum
     * @param customTypes            dialect-specific custom type overrides, or {@code null}
     * @param typeHandlerClasses     dialect-specific type handler class overrides, or {@code null}
     * @return a new column reference
     */
    static <T> QColumn<T> regular(
            final Class<T> javaType,
            final String tableAlias,
            final String alias,
            final String propertyName,
            final String columnName,
            final boolean id,
            final boolean autoGenerated,
            final boolean sequenceGenerated,
            final SequenceGeneratorData sequenceGeneratorData,
            final ConverterData converterData,
            final boolean insertable,
            final boolean updatable,
            final boolean nullable,
            final boolean version,
            final EnumMappingType enumMappingType,
            final Map<String, String> customTypes,
            final Map<String, Class<?>> typeHandlerClasses
    ) {
        return new DefaultQColumn<>(
                javaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated,
                sequenceGeneratorData, converterData,
                insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses
        );
    }

    /**
     * Creates a column reference with an attached {@link io.github.thinkfastpl.harbororm.api.converter.AttributeConverter}.
     *
     * <p>The converter transforms between the entity Java type ({@code T}) and the database Java type ({@code C}).
     *
     * @param <T>                    the entity-side Java type
     * @param <C>                    the database-side Java type
     * @param convertJavaType        the entity Java class
     * @param dbJavaType             the database Java class
     * @param tableAlias             the table alias, or {@code null}
     * @param alias                  the column alias, or {@code null}
     * @param propertyName           the entity property name, or {@code null}
     * @param columnName             the database column name
     * @param id                     whether this is the primary key column
     * @param autoGenerated          whether the value is database-generated
     * @param sequenceGenerated      whether the value is sequence-generated
     * @param sequenceGeneratorData  sequence metadata, or {@code null}
     * @param converterData          converter metadata
     * @param insertable             whether included in INSERT statements
     * @param updatable              whether included in UPDATE statements
     * @param nullable               whether the column allows NULL
     * @param version                whether this is the optimistic lock version column
     * @param enumMappingType        the enum mapping strategy, or {@code null}
     * @param customTypes            dialect-specific custom type overrides, or {@code null}
     * @param typeHandlerClasses     dialect-specific type handler class overrides, or {@code null}
     * @return a new converted column reference
     */
    static <T, C> QColumnConverted<T, C> converted(
            final Class<T> convertJavaType,
            final Class<C> dbJavaType,
            final String tableAlias,
            final String alias,
            final String propertyName,
            final String columnName,
            final boolean id,
            final boolean autoGenerated,
            final boolean sequenceGenerated,
            final SequenceGeneratorData sequenceGeneratorData,
            final ConverterData converterData,
            final boolean insertable,
            final boolean updatable,
            final boolean nullable,
            final boolean version,
            final EnumMappingType enumMappingType,
            final Map<String, String> customTypes,
            final Map<String, Class<?>> typeHandlerClasses
    ) {
        return new ConvertedQColumn<>(
                convertJavaType, dbJavaType, tableAlias, alias, propertyName, columnName,
                id, autoGenerated, sequenceGenerated,
                sequenceGeneratorData, converterData,
                insertable, updatable, nullable, version,
                enumMappingType, customTypes, typeHandlerClasses
        );
    }

    /**
     * Creates a minimal column reference with only the type, table alias, and column name.
     *
     * <p>The column is non-insertable, non-updatable, nullable, and has no converter or enum mapping.
     * Useful for ad-hoc column references in raw SQL queries.
     *
     * @param <T>        the Java type of the column
     * @param javaType   the Java class of the column value
     * @param tableAlias the table alias, or {@code null}
     * @param columnName the database column name
     * @return a new simple column reference
     */
    static <T> QColumn<T> simple(
            final Class<T> javaType,
            final String tableAlias,
            final String columnName
    ) {
        return regular(
                javaType,
                tableAlias,
                null,
                null,
                columnName,
                false,
                false,
                false,
                null,
                null,
                false,
                false,
                true,
                false,
                null,
                null,
                null
        );
    }

    /**
     * Creates a column reference for use in an {@code @ElementCollection} table.
     *
     * <p>The column is insertable, updatable, non-nullable, and has no table alias or property name.
     *
     * @param <T>             the Java type of the collection element
     * @param javaType        the Java class of the element
     * @param columnName      the database column name in the collection table
     * @param converterData   converter metadata, or {@code null}
     * @param enumMappingType the enum mapping strategy, or {@code null}
     * @param customTypes            dialect-specific custom type overrides, or {@code null}
     * @param typeHandlerClasses     dialect-specific type handler class overrides, or {@code null}
     * @return a new column reference for an element collection
     */
    static <T> QColumn<T> onElementCollection(
            final Class<T> javaType,
            final String columnName,
            final ConverterData converterData,
            final EnumMappingType enumMappingType,
            final Map<String, String> customTypes,
            final Map<String, Class<?>> typeHandlerClasses
    ) {
        return regular(
                javaType,
                null,
                null,
                null,
                columnName,
                false,
                false,
                false,
                null,
                converterData,
                true,
                true,
                false,
                false,
                enumMappingType,
                customTypes,
                typeHandlerClasses
        );
    }

    /**
     * Creates a column reference derived from {@link JoinColumnData}.
     *
     * <p>Inherits the column name, field type, insertable, updatable, and nullable flags from the join column.
     *
     * @param joinColumnData the join column metadata to derive from
     * @return a new column reference matching the join column
     */
    static QColumn<?> of(@NonNull JoinColumnData joinColumnData) {
        return regular(
                joinColumnData.getFieldType(),
                null,
                null,
                null,
                joinColumnData.getName(),
                false,
                false,
                false,
                null,
                null,
                joinColumnData.isInsertable(),
                joinColumnData.isUpdatable(),
                joinColumnData.isNullable(),
                false,
                null,
                null,
                null
        );
    }
}
