// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.annotations;

import java.lang.annotation.*;

/**
 * Indicates that the ID value is generated by the database using an identity column
 * or auto-increment mechanism.
 *
 * <p>When an entity with this annotation is inserted, the database generates the ID
 * value automatically. After insertion, HarborORM retrieves the generated value and
 * populates it in the entity instance.
 *
 * <h2>Example</h2>
 * <pre>{@code
 * @Id
 * @AutoGenerated
 * private Long id;
 * }</pre>
 *
 * @see Id
 * @see SequenceGenerated
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface AutoGenerated {
}
