// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.annotations;

import java.lang.annotation.*;

/**
 * Marks a field as the primary key of an entity.
 *
 * <p>Every {@link Entity} must have exactly one field annotated with {@code @Id}.
 * The ID can be a simple type or an {@link Embedded} composite key.
 *
 * <h2>ID Generation Strategies</h2>
 * <ul>
 *   <li>Manual assignment - set the value before insert</li>
 *   <li>{@link AutoGenerated} - database auto-increment</li>
 *   <li>{@link SequenceGenerated} - database sequence</li>
 * </ul>
 *
 * <h2>Example</h2>
 * <pre>{@code
 * @Id
 * @AutoGenerated
 * private Long id;
 * }</pre>
 *
 * @see AutoGenerated
 * @see SequenceGenerated
 * @see Embedded
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Id {
}
