// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.api.annotations;

import java.lang.annotation.*;

/**
 * Indicates that the ID value is generated from a database sequence.
 *
 * <p>Before inserting an entity, HarborORM calls the specified sequence to obtain
 * the next value and sets it on the entity. This allows the ID to be known before
 * the INSERT statement executes.
 *
 * <h2>Example</h2>
 * <pre>{@code
 * @Id
 * @SequenceGenerated(sequence = "products_id_seq")
 * private Long id;
 * }</pre>
 *
 * @see Id
 * @see AutoGenerated
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface SequenceGenerated {

    /**
     * The name of the database sequence to use for ID generation.
     *
     * @return the sequence name
     */
    String sequence();
}
