// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.core;

import io.github.thinkfastpl.harbororm.api.metadata.QColumn;
import io.github.thinkfastpl.harbororm.api.metadata.QEmbeddable;
import io.github.thinkfastpl.harbororm.api.query.executor.QueryExecutor;
import io.github.thinkfastpl.harbororm.core.utils.HarborBeanUtils;
import lombok.NonNull;

import java.util.function.BiConsumer;

class AttributeHolderHandler {

    static void setColumns(@NonNull QueryExecutor executor, @NonNull AttributeExtractor extractor, Object bean, boolean forInsert, int defaultStreamFetchSize, @NonNull BiConsumer<QColumn<Object>, Object> setterConsumer) {
        for (QColumn<?> column : extractor.getColumns()) {
            if (forInsert && !column.isInsertable()) {
                continue;
            }
            if (!forInsert && (!column.isUpdatable() || column.isVersion())) {
                continue;
            }

            @SuppressWarnings("unchecked") final QColumn<Object> castedColumn = (QColumn<Object>) column;
            Object value = bean == null ? null : HarborBeanUtils.getPropertyValue(bean, column.getPropertyName());

            if (bean != null && value == null && column.isSequenceGenerated()) {
                value = executor.nextSequenceValue(column.getSequenceGeneratorMetadata().orElseThrow().sequenceName());
                HarborBeanUtils.setPropertyValue(bean, column.getPropertyName(), value);
            }

            if (value != null || !column.isAutoGenerated()) {
                setterConsumer.accept(castedColumn, value);
            }
        }

        for (QEmbeddable<?> qEmbeddable : extractor.getEmbeddables()) {
            Object embeddableBean = bean == null ? null : HarborBeanUtils.getPropertyValue(bean, qEmbeddable.getPropertyName());
            setColumns(executor, new AttributeExtractor(qEmbeddable), embeddableBean, forInsert, defaultStreamFetchSize, setterConsumer);
        }
    }
}
