// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.core;

import io.github.thinkfastpl.harbororm.api.LazyRef;
import io.github.thinkfastpl.harbororm.api.exception.OptimisticLockException;
import io.github.thinkfastpl.harbororm.api.expression.Condition;
import io.github.thinkfastpl.harbororm.api.expression.DSL;
import io.github.thinkfastpl.harbororm.api.expression.Expression;
import io.github.thinkfastpl.harbororm.api.lob.PortableBlob;
import io.github.thinkfastpl.harbororm.api.lob.PortableClob;
import io.github.thinkfastpl.harbororm.api.lob.PortableLobSupport;
import io.github.thinkfastpl.harbororm.api.metadata.*;
import io.github.thinkfastpl.harbororm.api.query.InsertQuery;
import io.github.thinkfastpl.harbororm.api.query.executor.QueryExecutor;
import io.github.thinkfastpl.harbororm.api.query.result.InsertResult;
import io.github.thinkfastpl.harbororm.api.query.result.Record;
import io.github.thinkfastpl.harbororm.core.utils.HarborBeanUtils;
import lombok.NonNull;

import java.util.*;
import java.util.function.Function;

class EntityHandler {

    static <T, ID> void insertEntity(@NonNull QueryExecutor executor, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, Map<JoinColumnData, Object> parentEntityJoinColumnData, int defaultStreamFetchSize) {
        AttributeExtractor entityAttributeExtractor = new AttributeExtractor(qEntity);

        InsertQuery insertQuery = new DefaultInsertQuery(executor);
        insertQuery.into(qEntity.getTableName());

        // Initialize @Version field to 0 if null
        qEntity.getVersionColumn().ifPresent(versionColumn -> {
            Object currentVersion = HarborBeanUtils.getPropertyValue(entity, versionColumn.getPropertyName());
            if (currentVersion == null) {
                Object zero = castVersionValue(0L, versionColumn.getJavaType());
                HarborBeanUtils.setPropertyValue(entity, versionColumn.getPropertyName(), zero);
            }
        });

        invokeCallback(qEntity, entity, QAttributeHolder::getPreInsertMethodName);

        // Set join column values on the entity bean before setColumns, so that
        // entity columns matching join columns produce the correct FK value.
        // Only add join columns separately if no matching entity column exists.
        Set<String> joinColumnNamesHandled = new HashSet<>();
        if (parentEntityJoinColumnData != null) {
            for (Map.Entry<JoinColumnData, Object> entry : parentEntityJoinColumnData.entrySet()) {
                String joinColumnName = entry.getKey().getName();
                for (QColumn<?> column : entityAttributeExtractor.getColumns()) {
                    if (column.getColumnName().equals(joinColumnName) && column.getPropertyName() != null) {
                        HarborBeanUtils.setPropertyValue(entity, column.getPropertyName(), entry.getValue());
                        joinColumnNamesHandled.add(joinColumnName);
                        break;
                    }
                }
            }
        }

        AttributeHolderHandler.setColumns(executor, entityAttributeExtractor, entity, true, defaultStreamFetchSize, insertQuery::set);

        if (parentEntityJoinColumnData != null) {
            parentEntityJoinColumnData.forEach((joinColumnData, o) -> {
                if (!joinColumnNamesHandled.contains(joinColumnData.getName())) {
                    @SuppressWarnings("unchecked") QColumn<Object> qColumn = (QColumn<Object>) joinColumnData.getQColumn();
                    insertQuery.set(qColumn, o);
                }
            });
        }

        InsertResult insertResult = insertQuery.execute();

        if (insertResult.generatedKeys().size() == 1) {
            Record record = insertResult.generatedKeys().get(0);

            for (QColumn<?> column : entityAttributeExtractor.getColumns()) {
                if (column.isAutoGenerated()) {
                    Object generatedValue = record.get(column);
                    HarborBeanUtils.setPropertyValue(entity, column.getPropertyName(), generatedValue);
                }
            }
        }

        insertCascades(executor, qEntity, entity, entityAttributeExtractor, defaultStreamFetchSize);

        invokeCallback(qEntity, entity, QAttributeHolder::getPostInsertMethodName);
    }

    private static <T, ID> void insertCascades(@NonNull QueryExecutor executor, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, AttributeExtractor attributeExtractor, int defaultStreamFetchSize) {
        for (QElementCollection<?> elementCollection : attributeExtractor.getElementCollections()) {
            ElementCollectionHandler.insert(executor, qEntity, entity, elementCollection, defaultStreamFetchSize);
        }

        for (QEntityRelation<?, ?> entityRelation : attributeExtractor.getEntityRelations()) {
            @SuppressWarnings("unchecked") QEntity<Object, Object> relatedQEntity = (QEntity<Object, Object>) entityRelation.getRelatedQEntity();
            Map<JoinColumnData, Object> entityJoinColumnData = JoinColumnUtils.getEntityJoinColumnData(qEntity, entity, entityRelation.getJoinColumns());

            switch (entityRelation.getType()) {
                case ONE_TO_MANY -> {
                    @SuppressWarnings("unchecked") List<Object> relatedEntities = (List<Object>) HarborBeanUtils.getPropertyValue(entity, entityRelation.getPropertyName());
                    if (relatedEntities != null) {
                        for (Object relatedEntity : relatedEntities) {
                            insertEntity(executor, relatedQEntity, relatedEntity, entityJoinColumnData, defaultStreamFetchSize);
                        }
                    }
                }
                case ONE_TO_ONE -> {
                    LazyRef<?> ref = (LazyRef<?>) HarborBeanUtils.getPropertyValue(entity, entityRelation.getPropertyName());
                    Object child = ref != null ? ref.get() : null;
                    if (child != null) {
                        insertEntity(executor, relatedQEntity, child, entityJoinColumnData, defaultStreamFetchSize);
                    }
                }
            }
        }

        for (QManyToMany<?> manyToMany : attributeExtractor.getManyToManyRelations()) {
            ManyToManyHandler.insert(executor, qEntity, entity, manyToMany);
        }
    }

    static <T, ID> void insertEntityBatch(@NonNull QueryExecutor executor, @NonNull QEntity<T, ID> qEntity, @NonNull Collection<T> entities, int batchSize, int defaultStreamFetchSize) {
        if (batchSize < 1) {
            throw new IllegalArgumentException("Batch size must be greater than 0");
        }

        final Iterator<T> iterator = entities.iterator();
        final AttributeExtractor attributeExtractor = new AttributeExtractor(qEntity);

        final List<QColumn<?>> autoGeneratedColumns = attributeExtractor.getColumns().stream()
                .filter(QColumn::isAutoGenerated)
                .toList();

        executor.executeOnSingleConnection(singleConnectionQueryExecutor -> {
            while (iterator.hasNext()) {
                InsertQuery insertQuery = new DefaultInsertQuery(singleConnectionQueryExecutor);
                insertQuery.into(qEntity.getTableName());

                List<T> batchEntities = new ArrayList<>();
                for (int i = 0; i < batchSize && iterator.hasNext(); i++) {
                    final T entity = iterator.next();
                    batchEntities.add(entity);

                    insertQuery.nextRow();

                    // Initialize @Version field to 0 if null
                    qEntity.getVersionColumn().ifPresent(versionColumn -> {
                        Object currentVersion = HarborBeanUtils.getPropertyValue(entity, versionColumn.getPropertyName());
                        if (currentVersion == null) {
                            Object zero = castVersionValue(0L, versionColumn.getJavaType());
                            HarborBeanUtils.setPropertyValue(entity, versionColumn.getPropertyName(), zero);
                        }
                    });

                    invokeCallback(qEntity, entity, QAttributeHolder::getPreInsertMethodName);
                    AttributeHolderHandler.setColumns(singleConnectionQueryExecutor, attributeExtractor, entity, true, defaultStreamFetchSize, insertQuery::set);
                }

                List<Record> generatedKeys;

                if (autoGeneratedColumns.isEmpty()) {
                    generatedKeys = insertQuery.execute().generatedKeys();
                } else {
                    //noinspection unchecked
                    insertQuery.returning((List<Expression<?>>) (Object) autoGeneratedColumns);

                    generatedKeys = insertQuery.executeAndFetchAll();
                }

                for (int i = 0; i < batchEntities.size(); i++) {
                    T entity = batchEntities.get(i);

                    if (i < generatedKeys.size()) {
                        Record record = generatedKeys.get(i);
                        for (QColumn<?> column : autoGeneratedColumns) {
                            Object generatedValue = record.get(column);
                            HarborBeanUtils.setPropertyValue(entity, column.getPropertyName(), generatedValue);
                        }
                    }

                    insertCascades(executor, qEntity, entity, attributeExtractor, defaultStreamFetchSize);
                    invokeCallback(qEntity, entity, QAttributeHolder::getPostInsertMethodName);
                }
            }
        });
    }

    static <T, ID> void updateEntity(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, int lazyLoadBatchSize, int defaultStreamFetchSize) {
        updateEntityInternal(executor, portableLobSupport, qEntity, entity, true, lazyLoadBatchSize, defaultStreamFetchSize);
    }

    private static <T, ID> void updateEntityInternal(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, boolean checkVersion, int lazyLoadBatchSize, int defaultStreamFetchSize) {
        final QComparableAttribute<ID> idColumn = qEntity.getIdColumn();

        final ID id = HarborBeanUtils.getPropertyValue(entity, idColumn.getPropertyName(), idColumn.getJavaType());
        if (id == null) {
            throw new IllegalArgumentException("Entity with null ID is not allowed");
        }

        final DefaultUpdateQuery query = new DefaultUpdateQuery(executor);
        query.table(qEntity.getTableName());

        AttributeExtractor attributeExtractor = new AttributeExtractor(qEntity);

        invokeCallback(qEntity, entity, QAttributeHolder::getPreUpdateMethodName);
        AttributeHolderHandler.setColumns(executor, attributeExtractor, entity, false, defaultStreamFetchSize, query::set);

        // Optimistic locking: add version check to WHERE and increment in SET
        Optional<QColumn<?>> versionColumnOpt = checkVersion ? qEntity.getVersionColumn() : Optional.empty();
        if (versionColumnOpt.isPresent()) {
            @SuppressWarnings("unchecked") QColumn<Object> versionColumn = (QColumn<Object>) versionColumnOpt.get();
            Object currentVersion = HarborBeanUtils.getPropertyValue(entity, versionColumn.getPropertyName());
            if (currentVersion == null) {
                throw new IllegalArgumentException("@Version field must not be null on update");
            }

            // SET version = version + 1
            setVersionIncrement(query, versionColumn);

            // WHERE id = ? AND version = ?
            int rowsUpdated = query
                    .where(idColumn.eq(id), versionColumn.eq(currentVersion))
                    .execute();

            if (rowsUpdated == 0) {
                throw new OptimisticLockException(qEntity.getBeanType(), id, currentVersion);
            }

            // Update in-memory version
            long newVersion = toVersionLong(currentVersion) + 1;
            HarborBeanUtils.setPropertyValue(entity, versionColumn.getPropertyName(),
                    castVersionValue(newVersion, versionColumn.getJavaType()));
        } else {
            query
                    .where(idColumn.eq(id))
                    .execute();
        }

        for (QElementCollection<?> elementCollection : attributeExtractor.getElementCollections()) {
            if (ElementCollectionHandler.isPotentiallyModified(qEntity, entity, elementCollection)) {
                ElementCollectionHandler.delete(executor, qEntity, entity, elementCollection);
                ElementCollectionHandler.insert(executor, qEntity, entity, elementCollection, defaultStreamFetchSize);
            }
        }

        for (QEntityRelation<?, ?> entityRelation : attributeExtractor.getEntityRelations()) {
            @SuppressWarnings("unchecked") QEntity<Object, Object> relatedQEntity = (QEntity<Object, Object>) entityRelation.getRelatedQEntity();

            switch (entityRelation.getType()) {
                case ONE_TO_MANY -> {
                    @SuppressWarnings("unchecked") List<Object> relatedEntities = (List<Object>) HarborBeanUtils.getPropertyValue(entity, entityRelation.getPropertyName());
                    if (isPotentiallyModified(relatedEntities)) {
                        Map<JoinColumnData, Object> entityJoinColumnData = JoinColumnUtils.getEntityJoinColumnData(qEntity, entity, entityRelation.getJoinColumns());
                        for (Object relatedEntity : relatedEntities) {
                            replaceEntity(executor, portableLobSupport, relatedQEntity, relatedEntity, entityJoinColumnData, lazyLoadBatchSize, defaultStreamFetchSize);
                        }
                        if (relatedEntities instanceof LazyList lazyList) {
                            lazyList.getMissingEntities().forEach(missingEntity ->
                                    deleteEntity(executor, portableLobSupport, relatedQEntity, missingEntity)
                            );
                        }
                    }
                }
                case ONE_TO_ONE -> {
                    LazyRef<?> ref = (LazyRef<?>) HarborBeanUtils.getPropertyValue(entity, entityRelation.getPropertyName());
                    if (ref instanceof TrackableLazyRef trackable && trackable.isPotentiallyModified()) {
                        Map<JoinColumnData, Object> entityJoinColumnData = JoinColumnUtils.getEntityJoinColumnData(qEntity, entity, entityRelation.getJoinColumns());
                        Object relatedEntity = ref.get();
                        if (relatedEntity != null) {
                            replaceEntity(executor, portableLobSupport, relatedQEntity, relatedEntity, entityJoinColumnData, lazyLoadBatchSize, defaultStreamFetchSize);
                        }
                    } else if (!(ref instanceof TrackableLazyRef)) { // got replaced
                        Map<JoinColumnData, Object> entityJoinColumnData = JoinColumnUtils.getEntityJoinColumnData(qEntity, entity, entityRelation.getJoinColumns());

                        // delete if exists
                        {
                            // Build condition to find existing child by join column values
                            List<Condition> joinConditions = new ArrayList<>();
                            for (JoinColumnData joinColumn : entityRelation.getJoinColumns()) {
                                @SuppressWarnings("unchecked") QColumn<Object> jcColumn = (QColumn<Object>) joinColumn.getQColumn();
                                joinConditions.add(jcColumn.eq(entityJoinColumnData.get(joinColumn)));
                            }

                            List<Object> existingChildren = new DefaultEntityQuery<>(executor, relatedQEntity, lazyLoadBatchSize, defaultStreamFetchSize)
                                    .where(DSL.and(joinConditions))
                                    .fetchAll();

                            Object existingChild = existingChildren.isEmpty() ? null : existingChildren.get(0);
                            if (existingChild != null) {
                                deleteEntity(executor, portableLobSupport, relatedQEntity, existingChild);
                            }
                        }

                        // insert new if set
                        Object newChild = ref != null ? ref.get() : null;
                        if (newChild != null) {
                            insertEntity(executor, relatedQEntity, newChild, entityJoinColumnData, defaultStreamFetchSize);
                        }
                    }
                }
            }
        }

        for (QManyToMany<?> manyToMany : attributeExtractor.getManyToManyRelations()) {
            ManyToManyHandler.update(executor, qEntity, entity, manyToMany);
        }

        invokeCallback(qEntity, entity, QAttributeHolder::getPostUpdateMethodName);
    }

    static <T, ID> void replaceEntity(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, int lazyLoadBatchSize, int defaultStreamFetchSize) {
        replaceEntity(executor, portableLobSupport, qEntity, entity, Collections.emptyMap(), lazyLoadBatchSize, defaultStreamFetchSize);
    }

    static <T, ID> void replaceEntity(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull T entity, Map<JoinColumnData, Object> parentEntityJoinColumnData, int lazyLoadBatchSize, int defaultStreamFetchSize) {
        final QComparableAttribute<ID> idColumn = qEntity.getIdColumn();

        final ID id = HarborBeanUtils.getPropertyValue(entity, idColumn.getPropertyName(), idColumn.getJavaType());
        if (id == null || !new DefaultEntityQuery<>(executor, qEntity, lazyLoadBatchSize, defaultStreamFetchSize).whereIdEq(id).exists()) {
            insertEntity(executor, qEntity, entity, parentEntityJoinColumnData, defaultStreamFetchSize);
        } else {
            // No version checks on replace — upsert semantics per design
            updateEntityInternal(executor, portableLobSupport, qEntity, entity, false, lazyLoadBatchSize, defaultStreamFetchSize);
        }
    }

    static boolean simpleDeletionPermitted(@NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<?, ?> qEntity) {
        for (QAttribute qAttribute : qEntity.getAllAttributes()) {
            if (qAttribute instanceof QColumn<?> qColumn) {
                if (portableLobSupport.requiresManualBlobDeletion() && PortableBlob.class.isAssignableFrom(qColumn.getJavaType())) {
                    return false;
                }
                if (portableLobSupport.requiresManualClobDeletion() && PortableClob.class.isAssignableFrom(qColumn.getJavaType())) {
                    return false;
                }
            } else if (qAttribute instanceof QEntityRelation<?, ?>) {
                return false;
            } else if (qAttribute instanceof QElementCollection<?>) {
                return false;
            } else if (qAttribute instanceof QManyToMany<?>) {
                return false;
            }
        }
        return true;
    }

    static <T, ID> void deleteEntity(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull T entity) {
        deleteEntities(executor, portableLobSupport, qEntity, Collections.singletonList(entity));
    }

    @SuppressWarnings("unchecked")
    static <T, ID> void deleteEntities(@NonNull QueryExecutor executor, @NonNull PortableLobSupport portableLobSupport, @NonNull QEntity<T, ID> qEntity, @NonNull Collection<T> entities) {
        if (entities.isEmpty()) {
            return;
        }

        final QComparableAttribute<ID> idColumn = qEntity.getIdColumn();

        final List<ID> ids = entities.stream()
                .map(entity -> {
                    final ID id = HarborBeanUtils.getPropertyValue(entity, idColumn.getPropertyName(), idColumn.getJavaType());
                    if (id == null) {
                        throw new IllegalArgumentException("Entity with null ID is not allowed");
                    }
                    return id;
                })
                .toList();

        for (T entity : entities) {
            invokeCallback(qEntity, entity, QAttributeHolder::getPreDeleteMethodName);
        }

        for (QAttribute qAttribute : qEntity.getAllAttributes()) {
            if (qAttribute instanceof QColumn<?> qColumn) {
                if (portableLobSupport.requiresManualBlobDeletion() && PortableBlob.class.isAssignableFrom(qColumn.getJavaType())) {
                    for (T entity : entities) {
                        final PortableBlob portableBlob = (PortableBlob) HarborBeanUtils.getPropertyValue(entity, qColumn.getPropertyName());
                        if (portableBlob != null) {
                            portableLobSupport.deleteBlob(portableBlob);
                        }
                    }
                } else if (portableLobSupport.requiresManualClobDeletion() && PortableClob.class.isAssignableFrom(qColumn.getJavaType())) {
                    for (T entity : entities) {
                        final PortableClob portableClob = (PortableClob) HarborBeanUtils.getPropertyValue(entity, qColumn.getPropertyName());
                        if (portableClob != null) {
                            portableLobSupport.deleteClob(portableClob);
                        }
                    }
                }
            } else if (qAttribute instanceof QEntityRelation<?, ?> qEntityRelation) {
                QEntity<Object, Object> relatedQEntity = (QEntity<Object, Object>) qEntityRelation.getRelatedQEntity();

                switch (qEntityRelation.getType()) {
                    case ONE_TO_MANY -> {
                        List<Object> relatedEntities = new ArrayList<>();
                        for (T entity : entities) {
                            final var related = (List<Object>) HarborBeanUtils.getPropertyValue(entity, qEntityRelation.getPropertyName());
                            if (related != null) {
                                relatedEntities.addAll(related);
                            }
                        }
                        deleteEntities(executor, portableLobSupport, relatedQEntity, relatedEntities);
                    }
                    case ONE_TO_ONE -> {
                        List<Object> relatedEntities = new ArrayList<>();
                        for (T entity : entities) {
                            LazyRef<?> ref = (LazyRef<?>) HarborBeanUtils.getPropertyValue(entity, qEntityRelation.getPropertyName());
                            if (ref != null) {
                                Object child = ref.get();
                                if (child != null) {
                                    relatedEntities.add(child);
                                }
                            }
                        }
                        deleteEntities(executor, portableLobSupport, relatedQEntity, relatedEntities);
                    }
                }
            }
        }

        ElementCollectionHandler.delete(executor, qEntity, entities);
        ManyToManyHandler.delete(executor, qEntity, entities);

        // Build delete condition
        Condition deleteCondition = ids.size() == 1 ? idColumn.eq(ids.get(0)) : idColumn.in(ids);

        // Optimistic locking on single-entity delete
        Optional<QColumn<?>> versionColumnOpt = qEntity.getVersionColumn();
        if (versionColumnOpt.isPresent() && entities.size() == 1) {
            @SuppressWarnings("unchecked") QColumn<Object> versionColumn = (QColumn<Object>) versionColumnOpt.get();
            T singleEntity = entities.iterator().next();
            Object currentVersion = HarborBeanUtils.getPropertyValue(singleEntity, versionColumn.getPropertyName());

            if (currentVersion != null) {
                deleteCondition = DSL.and(deleteCondition, versionColumn.eq(currentVersion));
            }

            int rowsDeleted = new DefaultDeleteQuery(executor)
                    .from(qEntity.getTableName())
                    .where(deleteCondition)
                    .execute();

            if (rowsDeleted == 0) {
                throw new OptimisticLockException(qEntity.getBeanType(), ids.get(0), currentVersion);
            }
        } else {
            new DefaultDeleteQuery(executor)
                    .from(qEntity.getTableName())
                    .where(deleteCondition)
                    .execute();
        }

        for (T entity : entities) {
            invokeCallback(qEntity, entity, QAttributeHolder::getPostDeleteMethodName);
        }
    }

    private static void invokeCallback(@NonNull QAttributeHolder qAttributeHolder, Object bean, Function<QAttributeHolder, Optional<String>> callbackGetter) {
        for (QAttribute qAttribute : qAttributeHolder.getAllAttributes()) {
            if (qAttribute instanceof QEmbeddable<?> qEmbeddable) {
                Object embeddableBean = HarborBeanUtils.getPropertyValue(bean, qEmbeddable.getPropertyName());
                if (embeddableBean != null) {
                    invokeCallback(qEmbeddable, embeddableBean, callbackGetter);
                }
            }

            if (qAttribute instanceof QElementCollection<?> qElementCollection && qElementCollection.getAttribute() instanceof QEmbeddable<?> qEmbeddable) {
                @SuppressWarnings("unchecked") List<Object> embeddableBeans = (List<Object>) HarborBeanUtils.getPropertyValue(bean, qElementCollection.getPropertyName());
                if (embeddableBeans != null) {
                    for (Object embeddableBean : embeddableBeans) {
                        if (embeddableBean != null) {
                            invokeCallback(qEmbeddable, embeddableBean, callbackGetter);
                        }
                    }
                }
            }
        }

        callbackGetter.apply(qAttributeHolder)
                .ifPresent(methodName -> HarborBeanUtils.callMethod(bean, methodName));
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static void setVersionIncrement(DefaultUpdateQuery query, QColumn<?> versionColumn) {
        // Uses raw types to avoid ambiguity between set(QColumn<C>, Expression<C>) and set(QColumn<C>, C) when C=Object
        QColumn col = versionColumn;
        Expression constantOne = new io.github.thinkfastpl.harbororm.api.expression.ConstantExpression(versionColumn.getJavaType(), 1);
        Expression incrementExpr = col.add(constantOne);
        query.setRaw(versionColumn, incrementExpr);
    }

    private static Object castVersionValue(long value, Class<?> type) {
        if (type == Long.class || type == long.class) return value;
        if (type == Integer.class || type == int.class) return (int) value;
        if (type == Short.class || type == short.class) return (short) value;
        throw new IllegalStateException("Unsupported @Version type: " + type);
    }

    private static long toVersionLong(Object value) {
        return ((Number) value).longValue();
    }

    private static boolean isPotentiallyModified(List<Object> relatedEntities) {
        if (relatedEntities == null) {
            return false;
        }

        if (relatedEntities instanceof LazyList lazyList) {
            return lazyList.isPotentiallyModified();
        }

        return true;
    }
}
