// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.test.domain;

import io.github.thinkfastpl.harbororm.api.annotations.*;
import io.github.thinkfastpl.harbororm.api.dialect.StandardDialects;
import lombok.*;

import java.util.List;

@Entity(table = "roles")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@AllArgsConstructor
public class RoleEntity {

    @Id
    @AutoGenerated
    private Long id;

    @Column(nullable = false)
    private String name;

    @ElementCollection(
            table = "role_permissions",
            joinColumns = @JoinColumn(name = "role_id", fieldType = Long.class)
    )
    private List<
            @Column(name = "permission", nullable = false)
            @Type(dialect = StandardDialects.POSTGRES, columnType = "role_permission")
            @Enumerated RolePermission> permissions;
}
