// SPDX-License-Identifier: Apache-2.0

package io.github.thinkfastpl.harbororm.modelgen.metadata;

import io.github.thinkfastpl.harbororm.api.metadata.EnumMappingType;
import io.github.thinkfastpl.harbororm.modelgen.source.SourceRefType;
import io.github.thinkfastpl.harbororm.modelgen.utils.StringUtils;

public record ColumnMetadata(
        String fieldName,
        String columnName,
        boolean id,
        boolean autoGenerated,
        SequenceGeneratorMetadata sequenceGenerator,
        ConverterMetadata converterMetadata,
        boolean insertable,
        boolean updatable,
        boolean nullable,
        SourceRefType type,
        EnumMappingType enumMappingType,
        TypesMetadata typesMetadata,
        boolean version,
        boolean json,
        TypeHandlerMetadata typeHandlerMetadata,
        boolean explicitColumnName
) {

    public ColumnMetadata assureFieldName() {
        if (fieldName != null) {
            return this;
        }

        return new ColumnMetadata(
                StringUtils.toCamelCase(columnName),
                columnName,
                id,
                autoGenerated,
                sequenceGenerator,
                converterMetadata,
                insertable,
                updatable,
                nullable,
                type,
                enumMappingType,
                typesMetadata,
                version,
                json,
                typeHandlerMetadata,
                explicitColumnName
        );
    }

    public ColumnMetadata withFieldNamePrefix(String prefix) {
        return new ColumnMetadata(
                StringUtils.isNotBlank(prefix) ? prefix + StringUtils.ucFirst(fieldName) : fieldName,
                columnName,
                id,
                autoGenerated,
                sequenceGenerator,
                converterMetadata,
                insertable,
                updatable,
                nullable,
                type,
                enumMappingType,
                typesMetadata,
                version,
                json,
                typeHandlerMetadata,
                explicitColumnName
        );
    }
}
